### list all developers
GET http://localhost:3001/developers
Content-Type: application/json

### get a developer by id
GET http://localhost:3001/developers/dev_5bVeg2N1IsEaII3lcMjJ8

### create a developer
POST http://localhost:3001/developers
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "dateOfBirth": "1990-01-01"
}

### Patch a developer
PATCH http://localhost:3001/developers/dev_5bVeg2N1IsEaII3lcMjJ8
Content-Type: application/json

{
    "name": "John teste"
}

### Delete a developer
DELETE http://localhost:3001/developers/22

